### ISSUE TITLE
One issue

### ISSUE THREAD

**Issue by quiret** [Fernando-A-Rocha/mta-add-models#1]
**Found issues in version 1.1.0**

- if there are two peds synced for the player and both have the same custom model assigned to them, then if one of them streams out your syncer attempts to release the custom model for both of the ped elements, especially the one already streamed in. While the documentation of engineFreeModel does not mention what happens in this case, I assume that the request fails. This scenario is a potential model ID leak (the client will run out of available real model IDs at some point). Even worse: the client could run out of RAM very quickly.

**Moved suggestions to:** https://github.com/Fernando-A-Rocha/mta-add-models/issues/3

https://forum.mtasa.com/topic/133212-rel-add-new-models-library/#comment-1003406

**Comment by Fernando-A-Rocha** [comment]
Thank you for the challenges, sound really fun! Will let you know what I decide to work on asap.

**Comment by Fernando-A-Rocha** [comment]
> * if there are two peds synced for the player and both have the same custom model assigned to them, then if one of them streams out your syncer attempts to release the custom model for both of the ped elements, especially the one already streamed in.

I can confirm this issue does indeed happen. I forgot to make it check when an element streams out if there is need for freeing the model. There should only be need for freeing the model if no other streamed elements are using the same model.

> * While the documentation of engineFreeModel does not mention what happens in this case, I assume that the request fails. This scenario is a potential model ID leak (the client will run out of available real model IDs at some point). Even worse: the client could run out of RAM very quickly.

engineFreeModel only takes a model ID argument and frees that model ID, leaving all elements that had it with the model ID defined serverside when they were spawned (e.g. CJ skin when a ped was created). This in itself doesn't create model ID leaks as it frees the models properly. Please note that in no point in the client script I store the elements in an array, only the model IDs are stored, which are used by that function.

I will address the fact that the model is being freed incorrectly on streamOut, which can leave other elements of the same time with reset models if they had the same allocated ID.

**Comment by quiret** [comment]
> engineFreeModel only takes a model ID argument and frees that model ID, leaving all elements that had it with the model ID defined serverside when they were spawned (e.g. CJ skin when a ped was created). This in itself doesn't create model ID leaks as it frees the models properly. Please note that in no point in the client script I store the elements in an array, only the model IDs are stored, which are used by that function.

I see. In your script you seem to be assigning model IDs on the clientside only. But are you aware that server-side model IDs do not necessarily match client-side model IDs? You are not mentioning that peds with free'd model IDs are being reset to CJ on the clientside, which actually is the argument I made. So if engineFreeModel does not reset peds to CJ on the clientside, then it indeed is a resource leak.

**Comment by Fernando-A-Rocha** [comment]
I've found another issue: when a model ID is changed on an element detected via `onClientElementDataChange`, it does not check if the oldValue (aka old model ID) is no longer needed. I'm gonna make it so it frees it if no longer needed, same behavior when an element streams out.

**Comment by Fernando-A-Rocha** [comment]
@quiret Updated: Can you download the resource again and let me know how your testing goes now?

**Comment by Fernando-A-Rocha** [comment]
Also could you please put your suggestions separately into other issues? Thank you! 🙏

**Comment by quiret** [comment]
The original issue has been fixed. Good work!
