### ISSUE TITLE
[Help] Implement new models in gridlist

### ISSUE THREAD

**Issue by Sunlightcoder** [Fernando-A-Rocha/mta-add-models#11]
Hi there! About a month ago I found this resource-library for adding models to new custom `IDs`. I'm not very good at coding in the MTA, my resources were a simple usage of `engineReplaceModel`, the CEF panels etc. 
 So, more to the point, after seeing this project, I decided to port some vehicles from my copy of San Andreas with objects on new `IDs`  on local MTA server.
 Added a few of them, works great, thanks for such a great resource! Can you please help me create a simple MTA `guiGridlist` for vehicle spawns with a custom `ID`? Just a piece of code with an example of how  spawn "vehicle1" with not defualt `ID` by clicking on it in list, such as in the freeroam vehicle create menu. From this, I myself will figure out how to finish everything to an acceptable form for me.
 Anyway, somewhere this week, when I have a free minute, I'll try it myself. Thanks in advance!

**Comment by Sunlightcoder** [comment]
Ok, this was a way easier that i thought. Close issue.

**Comment by Fernando-A-Rocha** [comment]
> Ok, this was a way easier that i thought. Close issue.

@Sunlightcoder Hello first of all thank you for giving this resource a try! I appreciate the support.

I'm glad you're making your own scripts with it, I encourage you. Sorry for not having replied on time. You can reach out to me on Discord whenever if you have further questions/need guidance.

Nando#7736
