### ISSUE TITLE
Skin removed on respawn

### ISSUE THREAD

**Issue by Ironman1M** [Fernando-A-Rocha/mta-add-models#12]
The skin is removed on player respawn (looks like CJ) but element data is still set.

**Comment by Fernando-A-Rocha** [comment]
> The skin is removed on player respawn (looks like CJ) but element data is still set.

Hello @Ironman1M can you show me the piece of code that you use to respawn the player after he's dead?

**Comment by Fernando-A-Rocha** [comment]
I believe after you spawn the player and set the exact same skinID data it won't refresh and you'll be seeing CJ. I'll look into it.
