### ISSUE TITLE
Bug: Vehicle upgrades are lost on model change

### ISSUE THREAD

**Issue by mimimiguel** [Fernando-A-Rocha/mta-add-models#13]
STEPS TO REPRODUCE:
- Spawn any new car with this resource
- Add upgrades to it (addVehicleUpgrade...)
- Trigger a vehicle replacement, ex: reconnect, unload models, etc
- Get closer back to the car
- Upgrade is lost

Looking at the code, this seems to be similar to the issue with the handling, which you approached already. I can apply a similar fix to this if it's okey to you! 

I will update this issue with any progress I make.

**Comment by Fernando-A-Rocha** [comment]
Hello thank you for reporting this! You are right, a similar approach to the one I made for handling should work. Feel free to make a pull request 🙌
