### ISSUE TITLE
How to add Weapons (method)

### ISSUE THREAD

**Issue by 0f1** [Fernando-A-Rocha/mta-add-models#29]
i wanted to know if it's possible to add weapons ? tried to add it as a object but it needs a collision file.

**Comment by Fernando-A-Rocha** [comment]
> i wanted to know if it's possible to add weapons ? tried to add it as a object but it needs a collision file.

you can add objects without collision by doing ignoreCOL = true in the adding function

And to answer your question, yes you can add weapons but it's tricky, you need to make a script to support it.
You can indeed achieve it by adding objects and attaching them to the player (with pAttach for example) and hiding the default weapon (with shader set alpha 0, for example).

I haven't done this in a long time, so I don't know exactly how to make the script, but from what I remember the information above should help you ^^
