### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by quiret** [Fernando-A-Rocha/mta-add-models#3]
1. add a custom model cache based on usage frequency, API hinting (setCustomModelAlwaysLoaded) or database flag so that MTA does not have to perform the expensive disk loading of model data as frequently (improves FPS)

2. add statistics API about the number of custom models loaded, their usage details (frequency, number of elements with the model, etc) and the general performance of the resource. You could even add a debug dashboard using some hidden key combination (very important to build user-trust into your resource workings)

3. **(DONE)** add a way to register custom models from other storage resources. This way custom models could potentially be downloaded from the server on-demand by a second resource and - after finishing the download - be registered as custom model inside of your own resource. Could be really fun!

(( Edit: added number for each suggestion ))
(( Edit 2: marked suggestion 3 as done ))

**Comment by Fernando-A-Rocha** [comment]
> 2\. add a way to register custom models from other storage resources. This way custom models could potentially be downloaded from the server on-demand by a second resource and - after finishing the download - be registered as custom model inside of your own resource. Could be really fun!

Smart idea, I've made changes to allow this to be implemented very soon in [this commit](https://github.com/Fernando-A-Rocha/mta-add-models/commit/726d2fbb34a3857530eb73813cef0e8948c122d6)

**Comment by httpRick** [comment]
Please add that after removeElementData, it released the Model allocation and restored the original Element model.

**Comment by Fernando-A-Rocha** [comment]
3. and 4. done, check [this commit](https://github.com/Fernando-A-Rocha/mta-add-models/commit/e48afa0cf31f0419629d9c0296cc63f19c129ad6). @httpRick @quiret 

Please make one issue per suggestion next time, thank you <3

**Comment by Fernando-A-Rocha** [comment]
> 1. add a custom model cache based on usage frequency, API hinting (setCustomModelAlwaysLoaded) or database flag so that MTA does not have to perform the expensive disk loading of model data as frequently (improves FPS)

> 2. add statistics API about the number of custom models loaded, their usage details (frequency, number of elements with the model, etc) and the general performance of the resource. You could even add a debug dashboard using some hidden key combination (very important to build user-trust into your resource workings)

Suggestions accepted! Will be my first time making such features, so bear with me 😄

**Comment by Santiagotrululu** [comment]
Hola mi problema es que yo trabajo con la gm downtown entonse cualquier jugador puede utilizar el comando y otra cosas es que el carro,moto no queda guardada como carro positivo si no como negativo
