### ISSUE TITLE
Element models not released by destroyElement (issue?)

### ISSUE THREAD

**Issue by quiret** [Fernando-A-Rocha/mta-add-models#4]
If a streamed-in element is destroyed (for example using destroyElement) and it has a custom model association, then that custom model is not released. This is peculiar because your resource is releasing custom models on element-stream-out if these models are not used anymore. How about you try using the onClientElementDestroy event, too?

**Comment by Fernando-A-Rocha** [comment]
I think when they are destroyed they are streamed out, so it would be redundant @quiret

**Comment by Fernando-A-Rocha** [comment]
I will add a command to test & prove this.

**Comment by Fernando-A-Rocha** [comment]
After testing I noticed that onClientElementStreamOut is not called when element is destroyed, I thought this happened, sorry! Fixing.
