### ISSUE TITLE
This resource is potentially insecure

### ISSUE THREAD

**Issue by gtkvba** [Fernando-A-Rocha/mta-add-models#41]
Hey,
I recommend you to verify if elem data's such as vehicle handling etc. changes on the client and then kicking/flaging/banning player as it could be used from trainers to force unexpected behaviors.
U can do it using handle on event onElementDataChange and checking client parameter (so then its elem data changed on cside) along with key and indexing the table with protected serverside element datas such as handling.
My kindest regards,
Jakub

**Comment by Fernando-A-Rocha** [comment]
> Hey, I recommend you to verify if elem data's such as vehicle handling etc. changes on the client and then kicking/flaging/banning player as it could be used from trainers to force unexpected behaviors. U can do it using handle on event onElementDataChange and checking client parameter (so then its elem data changed on cside) along with key and indexing the table with protected serverside element datas such as handling. My kindest regards, Jakub

Hey, this resource will not act as anti cheat.
You should do this element data protection in your server's anti cheat.
Thank you for the comment nonetheless.
