### ISSUE TITLE
Add handing support for addon vehicle model

### ISSUE THREAD

**Issue by gta191977649** [Fernando-A-Rocha/mta-add-models#42]
Some vehicle model may have custom handing in order to make the use of it, i think we should add the support for it as well =)

**Comment by Fernando-A-Rocha** [comment]
> Some vehicle model may have custom handing in order to make the use of it, i think we should add the support for it as well =)

it is already supported automatically for vehicles created serverside with handling set server side & newmodel ids

**Comment by Fernando-A-Rocha** [comment]
https://github.com/Fernando-A-Rocha/mta-add-models/blob/main/newmodels/server.lua#L28 @gta191977649
