### ISSUE TITLE
Freeroam

### ISSUE THREAD

**Issue by oribeiro2k24** [Fernando-A-Rocha/mta-add-models#43]
o freeroam (painel f1) não ta dando spawn nos veiculos, como consigo fazer ele dar spawn?

**Comment by Fernando-A-Rocha** [comment]
> o freeroam (painel f1) não ta dando spawn nos veiculos, como consigo fazer ele dar spawn?

funciona tudo certo sim
vc pode mostrar o erro e explicar oq vc fez?

**Comment by oribeiro2k24** [comment]
n da spawn, clico em create e o veiculo nao sai

**Comment by oribeiro2k24** [comment]
ensina eu ai configura pa po moto
