### ISSUE TITLE
The trailer wheel won't engage!

### ISSUE THREAD

**Issue by BabyBeefDx** [Fernando-A-Rocha/mta-add-models#44]
The trailer wheel doesn't engage, the truck responsible for pulling the trailer can't engage anything if it's in the newmodels! Trailers can be on newmodels that work normally, but wheelies cannot!

**Comment by Fernando-A-Rocha** [comment]
@BabyBeefDx 
It is a known MTA issue that has already been reported and is awaiting a fix.
https://github.com/multitheftauto/mtasa-blue/issues/1861
