### ISSUE TITLE
Script security issue

### ISSUE THREAD

**Issue by thisdp** [Fernando-A-Rocha/mta-add-models#49]
At [678691c](https://github.com/Fernando-A-Rocha/mta-add-models/commit/678691c388445731b96e3e89dfd614fe1fb563bc)
File newmodels_reborn/scripts/core/shared_importfunc.lua, line 13:
`exportScriptString = fileRead(f, fileGetSize(f))`
This can cause lua injection, when other resources "loadstring" the "import()" result.
Use **fileGetContents** instead

**Comment by Fernando-A-Rocha** [comment]
thank u, u are right! fileGetContents will verify the checksum of the script
